[GITHUB-1089] Fix missing reflection use in `c.s.j.internal.ReflectionUtils`
`c.s.j.internal.ReflectionUtils` accesses `java.lang.invoke.MethodType`
without reflection, causing `java.lang.NoClassDefFoundError`
on android API level < 26

MethodType is already accessed via reflection and just for the method
lookup the class literal was used. The literal use was removed and
replaced with the class already looked up via reflection.